#tuned
fishing-v1:
  n_envs: 4
  n_timesteps: !!float 3e5
  policy: 'MlpPolicy'
  batch_size: 8
  n_steps: 64
  gamma: 0.95
  learning_rate: 0.009063123943359215
  ent_coef: 0.002465145165808194
  clip_range: 0.4
  n_epochs: 5
  gae_lambda: 0.98
  max_grad_norm: 0.8
  vf_coef: 0.8153389910080954

#tuned
conservation-v6:
  n_envs: 4
  n_timesteps: !!float 3e5
  policy: 'MlpPolicy'
  batch_size: 64
  n_steps: 256
  gamma: 0.9
  learning_rate: 0.0008330851234475645
  ent_coef: 7.290496088342335e-08
  clip_range: 0.3
  n_epochs: 1
  gae_lambda: 0.95
  max_grad_norm: 0.5
  vf_coef: 0.7638921186547223
  policy_kwargs: "dict(activation_fn=nn.ReLU,
                       net_arch=[dict(pi=[256, 256], vf=[256, 256])]
                       )"

