---
output: pdf_document
header-includes:
  - \pagestyle{empty}
  - \geometry{margin=0in}
bibliography: ../manuscript/references.bib
suppress-bibliography: True
---
+-----------+-----------------------------------------------+-------------+------------+---------------+-------------------+
| Algorithm | Description                                   | Model Use   | Evaluation | Policy        | Method            |
+===========+===============================================+=============+============+===============+===================+
|    MBPO   | Model-based Policy Optimization [@mbpo]       | Model-based | On-policy  | Deterministic | Policy Gradient   |
+-----------+-----------------------------------------------+-------------+------------+---------------+-------------------+
|    MCTS   | Monte Carlo Tree Search [@suttonbarto]        | Model-based | Either     | Either        | Any               |
+-----------+-----------------------------------------------+-------------+------------+---------------+-------------------+
|    A2C    | Advantage Actor Critic [@A2C]                 | Model-free  | On-policy  | Stochastic    | Actor-critic      |
+-----------+-----------------------------------------------+-------------+------------+---------------+-------------------+
|    A3C    | Asynchronous A2C       [@a3c]                 | Model-free  | On-policy  | Stochastic    | Actor-critic      |
+-----------+-----------------------------------------------+-------------+------------+---------------+-------------------+
|    TRPO   | Trust Region Policy Optimization [@trpo]      | Model-free  | On-policy  | Stochastic    | Policy gradient   |
+-----------+-----------------------------------------------+-------------+------------+---------------+-------------------+
|    PPO    | Proximal Policy Optimization [@ppo]           | Model-free  | On-policy  | Stochastic    | Actor-critic      |
+-----------+-----------------------------------------------+-------------+------------+---------------+-------------------+
|    DQN    | Deep Q Networks [@DQN]                        |  Model-free | Off-policy | Deterministic | Value-based       |
+-----------+-----------------------------------------------+-------------+------------+---------------+-------------------+
|    DDPG   | Deep Deterministic Policy Gradient [@ddpg]    | Model-free  | Off-policy | Deterministic | Actor-critic      |
+-----------+-----------------------------------------------+-------------+------------+---------------+-------------------+
|    TD3    | Twin Delayed DDPG [@TD3]                      |  Model-free | Off-policy | Deterministic | Actor-critic      |
+-----------+-----------------------------------------------+-------------+------------+---------------+-------------------+
|    SAC    |  Soft Actor Critic [@sac]                     | Model-free  | Off-policy | Stochastic    | Actor-critic      |
+-----------+-----------------------------------------------+-------------+------------+---------------+-------------------+
|    IMPALA |Importance Weighted Actor Learner [@impala]    | Model-free  | Off-policy | Stochastic    | Actor-critic      |
+-----------+-----------------------------------------------+-------------+------------+---------------+-------------------+