
on: push

name: Render manuscript


jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      - uses: r-lib/actions/setup-tinytex@v2


      - name: Appendix
        run: |-
          Rscript -e "rmarkdown::render('appendices/appendix-B-examples.Rmd')"
      - name: Manuscript
        run: |-
          Rscript -e "rmarkdown::render('manuscript/manuscript.Rmd')"
