name: Docker Actions
on: [push]
jobs:
  my_job:
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |-
          /rocker_scripts/install_python.sh
          Rscript -e "renv::restore()"
      - name: Render all appendices
        run: |-
          Rscript -e "lapply(fs::dir_ls('appendices', glob='*.Rmd', recurse=TRUE), rmarkdown::render, envir = globalenv())"
      - name: Render manuscript
        run: |-
          Rscript -e "lapply(fs::dir_ls('manuscript', glob='manuscript.Rmd', recurse=TRUE), rmarkdown::render, envir = globalenv())"


